;
; RC702 BIOS loader stub — loaded by ROA375 PROM to low memory.
;
; The PROM reads track 0 sectors 6-26 (head 0, FM 128B) and
; sectors 1-26 (head 1, MFM 256B) into contiguous memory starting
; at the entry address from boot sector bytes 0-1.
;
; This stub is the first code loaded. It:
;   1. Disables interrupts
;   2. Copies the BIOS binary from its load position to 0xDA00
;   3. Jumps to 0xDA00 (BIOS cold boot entry)
;
; The BIOS binary follows immediately after this stub in the
; loaded data. Stub size must be accounted for in the copy.
;

; Loader stub — this file is reference only.
; The actual loader is generated by make-disk.py as raw machine code.
; See make_loader_stub() in make-disk.py for the implementation.
;
; The stub at 0x0280:
;   DI
;   LD HL, source       ; 0x0280 + 15
;   LD DE, 0xDA00
;   LD BC, bios_size
;   LDIR
;   JP 0xDA00
